/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
    WdCard: typeof import('@wot-ui/ui/components/wd-card/wd-card.vue')['WdCard']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
  const WdCard: typeof import('@wot-ui/ui/components/wd-card/wd-card.vue')['WdCard']
}